//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendPw
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGallery
    {
        public int id { get; set; }
        public int ProjectId { get; set; }
        public string imageType { get; set; }
        public string image { get; set; }
        public System.DateTime added { get; set; }
        public string addedBy { get; set; }
        public string imageThumbnail { get; set; }
    }
}
