//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendPw
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public System.DateTime Added { get; set; }
        public string AddedBy { get; set; }
        public string thumbnail { get; set; }
    }
}
